import os
import sys
import math

################################################################################
# CREATE LEF view for the given SRAM (routing-friendly version)
################################################################################

def create_lef(mem):
    """
    Generate a very routing-friendly LEF:
      - signal pins are inset from the edge
      - signal pins are big
      - no SHAPE ABUTMENT on signal pins
      - VDD/VSS are wide bars across the macro
      - OBS blocks only layers below the pin layer
    """

    # open output
    lef_path = os.path.join(mem.results_dir, mem.name + '.lef')
    fid = open(lef_path, 'w')

    # memory params
    name        = mem.name
    depth       = mem.depth
    bits        = mem.width_in_bits
    banks       = mem.num_banks
    w           = mem.width_um
    h           = mem.height_um
    addr_width  = math.ceil(math.log2(mem.depth))

    # process params
    min_pin_width         = mem.process.pin_width_um
    min_pin_pitch         = mem.process.pin_pitch_um
    manufacturing_grid_um = mem.process.manufacturing_grid_um
    metal_prefix          = mem.process.metal_prefix      # e.g. "metal"
    metal_layer           = mem.process.metal_layer       # e.g. "metal3"

    # offsets
    x_offset = 1.0 * min_pin_pitch   # used for supplies
    y_offset = 1.0 * min_pin_pitch

    # how many signal pins we need on the side
    # rd_out (bits) + wd_in (bits) + addr (addr_width) + we/ce/clk
    number_of_pins = 2 * bits + addr_width + 3

    # how many "tracks" vertically we have on the side
    number_of_tracks_available = math.floor((h - 2 * y_offset) / min_pin_pitch)
    number_of_spare_tracks = number_of_tracks_available - number_of_pins

    if number_of_spare_tracks < 0:
        print(
            "Error: not enough tracks (num pins: %d, available tracks: %d)." %
            (number_of_pins, number_of_tracks_available)
        )
        sys.exit(1)

    # try to spread pins if we have spare tracks
    track_count = 1
    while number_of_spare_tracks > 0:
        track_count += 1
        number_of_spare_tracks = (
            number_of_tracks_available - number_of_pins * track_count
        )
    track_count -= 1

    pin_pitch = min_pin_pitch * track_count

    # extra spacing between functional groups
    extra = math.floor(
        (number_of_tracks_available - number_of_pins * track_count) / 3
    )
    group_pitch = extra * min_pin_pitch

    # -------------------------------------------------------------------------
    # LEF header
    # -------------------------------------------------------------------------
    fid.write('# Generated by FakeRAM 2.0 (routing-friendly)\n')
    fid.write('VERSION 5.7 ;\n')
    fid.write('BUSBITCHARS "[]" ;\n')
    fid.write('PROPERTYDEFINITIONS\n')
    fid.write('  MACRO width INTEGER ;\n')
    fid.write('  MACRO depth INTEGER ;\n')
    fid.write('  MACRO banks INTEGER ;\n')
    fid.write('END PROPERTYDEFINITIONS\n')
    fid.write('MACRO %s\n' % name)
    fid.write('  PROPERTY width %d ;\n' % bits)
    fid.write('  PROPERTY depth %d ;\n' % depth)
    fid.write('  PROPERTY banks %d ;\n' % banks)
    fid.write('  FOREIGN %s 0 0 ;\n' % name)
    fid.write('  SYMMETRY X Y R90 ;\n')
    fid.write('  SIZE %.3f BY %.3f ;\n' % (w, h))
    fid.write('  CLASS BLOCK ;\n')

    # -------------------------------------------------------------------------
    # SIGNAL PINS
    # -------------------------------------------------------------------------
    # start y on grid
    y_step = (
        y_offset
        - (y_offset % manufacturing_grid_um)
        + (min_pin_width / 2.0)
    )

    # 1) read data
    for i in range(int(bits)):
        y_step = lef_add_pin(
            fid, mem, 'rd_out[%d]' % i, is_input=False,
            y=y_step, pitch=pin_pitch,
            x_inset=1.0  # 1um inside
        )

    # 2) write data
    y_step += group_pitch
    for i in range(int(bits)):
        y_step = lef_add_pin(
            fid, mem, 'wd_in[%d]' % i, is_input=True,
            y=y_step, pitch=pin_pitch,
            x_inset=1.0
        )

    # 3) address
    y_step += group_pitch
    for i in range(int(addr_width)):
        y_step = lef_add_pin(
            fid, mem, 'addr_in[%d]' % i, is_input=True,
            y=y_step, pitch=pin_pitch,
            x_inset=1.0
        )

    # 4) control pins
    y_step += group_pitch
    y_step = lef_add_pin(fid, mem, 'we_in',  True, y_step, pin_pitch, x_inset=1.0)
    y_step = lef_add_pin(fid, mem, 'ce_in',  True, y_step, pin_pitch, x_inset=1.0)
    y_step = lef_add_pin(fid, mem, 'clk',    True, y_step, pin_pitch, x_inset=1.0)

    # -------------------------------------------------------------------------
    # POWER / GROUND BARS (wide, easy to hit)
    # -------------------------------------------------------------------------
    supply_pin_width      = min_pin_width * 4
    supply_pin_half_width = supply_pin_width / 2.0
    supply_pin_pitch      = min_pin_pitch * 8

    # VSS
    y_step = y_offset
    fid.write('  PIN VSS\n')
    fid.write('    DIRECTION INOUT ;\n')
    fid.write('    USE GROUND ;\n')
    fid.write('    PORT\n')
    fid.write('      LAYER %s ;\n' % metal_layer)
    while y_step <= h - y_offset:
        fid.write(
            '      RECT %.3f %.3f %.3f %.3f ;\n'
            % (x_offset,
               y_step - supply_pin_half_width,
               w - x_offset,
               y_step + supply_pin_half_width)
        )
        # skip one slot for VDD
        y_step += supply_pin_pitch * 2
    fid.write('    END\n')
    fid.write('  END VSS\n')

    # VDD (interleaved)
    y_step = y_offset + supply_pin_pitch
    fid.write('  PIN VDD\n')
    fid.write('    DIRECTION INOUT ;\n')
    fid.write('    USE POWER ;\n')
    fid.write('    PORT\n')
    fid.write('      LAYER %s ;\n' % metal_layer)
    while y_step <= h - y_offset:
        fid.write(
            '      RECT %.3f %.3f %.3f %.3f ;\n'
            % (x_offset,
               y_step - supply_pin_half_width,
               w - x_offset,
               y_step + supply_pin_half_width)
        )
        y_step += supply_pin_pitch * 2
    fid.write('    END\n')
    fid.write('  END VDD\n')

    # -------------------------------------------------------------------------
    # OBS: block layers BELOW our pin layer, not the pin layer itself
    # -------------------------------------------------------------------------
    fid.write('  OBS\n')
    pin_layer_number = metal_layer.replace(metal_prefix, "", 1)
    try:
        pin_layer_index = int(pin_layer_number)
    except ValueError:
        # if metal_layer is weird, just assume it's the first routable layer
        pin_layer_index = 1

    block_layer_count = max(pin_layer_index - 1, 0)
    for x in range(block_layer_count):
        dummy = x + 1
        fid.write('    LAYER %s%d ;\n' % (metal_prefix, dummy))
        fid.write('    RECT 0 0 %.3f %.3f ;\n' % (w, h))
    fid.write('  END\n')

    # end macro / library
    fid.write('END %s\n' % name)
    fid.write('END LIBRARY\n')
    fid.close()


################################################################################
# Helper function: add a routing-friendly signal pin
################################################################################

def lef_add_pin(fid, mem, pin_name, is_input, y, pitch, x_inset=1.0):
    """
    Write a big, easy-to-route pin.
    - inset from x=0 so it isn't on the boundary
    - two PORTs (one larger) on the same layer
    """
    layer = mem.process.metal_layer

    # generous geometry
    x1 = x_inset
    x2 = x_inset + 2.0     # 2 um wide pad
    pw = mem.process.pin_width_um
    hpw = pw / 2.0

    fid.write('  PIN %s\n' % pin_name)
    fid.write('    DIRECTION %s ;\n' % ('INPUT' if is_input else 'OUTPUT'))
    fid.write('    USE SIGNAL ;\n')

    # main smallish port
    fid.write('    PORT\n')
    fid.write('      LAYER %s ;\n' % layer)
    fid.write('      RECT %.3f %.3f %.3f %.3f ;\n'
              % (x1, y - hpw, x2, y + hpw))
    fid.write('    END\n')

    # extra bigger landing pad on same layer
    fid.write('    PORT\n')
    fid.write('      LAYER %s ;\n' % layer)
    fid.write('      RECT %.3f %.3f %.3f %.3f ;\n'
              % (x1, y - pw, x2 + 1.0, y + pw))
    fid.write('    END\n')

    fid.write('  END %s\n' % pin_name)

    return y + pitch
