#!/usr/bin/env python3
"""
Convert Raphael DSPF output to SPEF format for multiple windows.

This script processes all windows in a directory, converting each all_nets.dspf
file to a corresponding W*.spef file in the output directory.

Example usage:
    python raphael_to_spef.py datasets/nangate45/small/out_raphael datasets/nangate45/small/labels_raphael

The script expects input directories to contain window subdirectories (W0, W1, etc.)
with all_nets.dspf files generated by Raphael capacitance extraction.
"""

from __future__ import annotations

import argparse
import sys
import os
from pathlib import Path
from typing import Dict, List, Optional, Tuple, Set
from collections import defaultdict
from tqdm import tqdm

DEFAULT_COUPLING_THRESHOLD_RATIO = 0.01  # 1% of self capacitance by default

# Add repository root to path for imports
REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))



def parse_raphael(lines: Iterable[str], *, drop_nets: List[str], threshold_f: float) -> Tuple[Dict[str, float], Dict[Tuple[str, str], float]]:
    """Parse Raphael DSPF capacitances into totals and couplings."""

    self_cap_f: Dict[str, float] = {}
    coupling_f: Dict[Tuple[str, str], float] = {}

    current_net: Optional[str] = None

    for raw in lines:
        line = raw.strip()
        if not line:
            continue

        if line.startswith("*|NET"):
            parts = line.split()
            if len(parts) >= 3:
                net = parts[1]
                try:
                    total = float(parts[2])
                except ValueError:
                    total = 0.0
                self_cap_f[net] = total
                current_net = net
            else:
                current_net = None
            continue

        if line.startswith("*|"):
            # Metadata line within the DSPF; ignore.
            continue

        if current_net is None or current_net in drop_nets:
            continue

        if not line or line[0] not in {"C", "c"}:
            continue

        parts = line.split()
        if len(parts) < 4:
            continue

        net_a = parts[1]
        net_b = parts[2]
        try:
            value = float(parts[-1])
        except ValueError:
            continue

        magnitude = abs(value)
        if magnitude < threshold_f:
            continue

        if net_a == current_net:
            other = net_b
        elif net_b == current_net:
            other = net_a
        else:
            # Unexpected ordering; skip to avoid mis-attribution.
            continue

        if other in drop_nets:
            continue

        key = tuple(sorted((current_net, other)))
        if key in coupling_f:
            coupling_f[key] = 0.5 * (coupling_f[key] + magnitude)
        else:
            coupling_f[key] = magnitude

    return self_cap_f, coupling_f


def align_with_spef_name_map(
    self_cap_f: Dict[str, float],
    coupling_f: Dict[Tuple[str, str], float],
    spef_lines: Iterable[str],
) -> Tuple[Dict[str, float], Dict[Tuple[str, str], float]]:
    align_names: Set[str] = set()
    in_name_map = False
    for raw in spef_lines:
        s = raw.rstrip("\n")
        if s.startswith("*NAME_MAP"):
            in_name_map = True
            continue
        if in_name_map:
            if not s.startswith("*") or s.startswith("*D_NET"):
                in_name_map = False
                continue
            parts = s.split(maxsplit=1)
            if len(parts) == 2:
                align_names.add(parts[1].strip())

    if not align_names:
        return self_cap_f, coupling_f

    def align_name(name: str) -> str:
        if name in align_names:
            return name
        candidate = name.replace(".", "")
        if candidate in align_names:
            return candidate
        base = name.split(".", 1)[0]
        if base in align_names:
            return base
        lowercase = name.lower()
        if lowercase in align_names:
            return lowercase
        if lowercase.replace(".", "") in align_names:
            return lowercase.replace(".", "")
        return name

    merged_self: Dict[str, float] = defaultdict(float)
    for name, total in self_cap_f.items():
        merged_self[align_name(name)] += total

    merged_coupling: Dict[Tuple[str, str], float] = {}
    for (i, j), value in coupling_f.items():
        ai = align_name(i)
        aj = align_name(j)
        if ai == aj:
            # Degenerate case (both ends collapse to same net); skip
            continue
        key = tuple(sorted((ai, aj)))
        if key in merged_coupling:
            merged_coupling[key] = 0.5 * (merged_coupling[key] + value)
        else:
            merged_coupling[key] = value

    return dict(merged_self), merged_coupling


def write_spef(
    out,
    *,
    design: str,
    nets: List[str],
    self_cap_f: Dict[str, float],
    coupling_f: Dict[Tuple[str, str], float],
    coupling_threshold_ratio: float = DEFAULT_COUPLING_THRESHOLD_RATIO,
) -> int:
    """Write SPEF format output."""
    # Header
    import datetime as _dt
    now = _dt.datetime.now().strftime("%H:%M:%S %A %B %d, %Y")
    print('*SPEF "ieee 1481-1999"', file=out)
    print(f'*DESIGN "{design}"', file=out)
    print(f'*DATE "{now}"', file=out)
    print('*VENDOR "RWCap-to-SPEF"', file=out)
    print('*PROGRAM "rwcap_to_spef"', file=out)
    print('*VERSION "1.0"', file=out)
    print('*DESIGN_FLOW "NAME_SCOPE LOCAL" "PIN_CAP NONE"', file=out)
    print('*DIVIDER /', file=out)
    print('*DELIMITER :', file=out)
    print('*BUS_DELIMITER []', file=out)
    print('*T_UNIT 1 NS', file=out)
    print('*C_UNIT 1 PF', file=out)
    print('*R_UNIT 1 OHM', file=out)
    print('*L_UNIT 1 HENRY', file=out)
    print(file=out)

    # Name map
    print('*NAME_MAP', file=out)
    for idx, net in enumerate(nets, start=1):
        print(f'*{idx} {net}', file=out)
    print(file=out)

    # Net data
    net_to_idx = {net: idx for idx, net in enumerate(nets, start=1)}
    # Add special mapping for GROUND to use index 1000+ for couplings
    # This follows openRCX conventions where GROUND appears in couplings but not as a regular net

    removed_couplings_count = 0

    for idx, net in enumerate(nets, start=1):
        # Total self capacitance in pF (convert from F)
        total_cap_pf = self_cap_f.get(net, 0.0) * 1e12
        print(f'*D_NET *{idx} {total_cap_pf:.6e}', file=out)
        print('*CONN', file=out)
        print(f'*P {net} B', file=out)
        print('*CAP', file=out)

        # Self capacitance (if available)
        if net in self_cap_f:
            self_cap_pf = self_cap_f[net] * 1e12
            print(f'{idx} {net} {self_cap_pf:.6e}', file=out)

        # Coupling capacitances with threshold filtering
        for (i, j), value_f in coupling_f.items():
            if i == net or j == net:
                other = j if i == net else i

                # Apply threshold filtering: skip coupling if it's less than threshold% of both nets' self capacitance
                self_cap_i = abs(self_cap_f.get(i, 0.0))
                self_cap_j = abs(self_cap_f.get(j, 0.0))

                # Skip if either net has zero self capacitance to avoid division by zero
                if self_cap_i == 0.0 or self_cap_j == 0.0:
                    continue

                threshold_i = self_cap_i * coupling_threshold_ratio
                threshold_j = self_cap_j * coupling_threshold_ratio

                # Only include coupling if it's above threshold for both nets
                if value_f >= threshold_i and value_f >= threshold_j:
                    # Handle GROUND couplings - include them even though GROUND is not in net_to_idx
                    if other in net_to_idx:
                        other_idx = net_to_idx[other]
                        cap_pf = value_f * 1e12
                        print(f'{idx+1000} {net} {other} {cap_pf:.6e}', file=out)
                    elif other == "GROUND":
                        # Special handling for GROUND couplings following openRCX conventions
                        cap_pf = value_f * 1e12
                        print(f'{idx+1000} {net} GROUND {cap_pf:.6e}', file=out)
                else:
                    removed_couplings_count += 1

        print('*RES', file=out)
        print('*END', file=out)
        print(file=out)

    return removed_couplings_count


def find_window_directories(input_dir: Path, pattern: str = "W*") -> List[Tuple[str, Path]]:
    """Find all window directories matching the pattern."""

    if not input_dir.is_dir():
        raise ValueError(f"Input directory not found: {input_dir}")

    window_dirs = []
    for window_dir in input_dir.glob(pattern):
        if window_dir.is_dir():
            window_id = window_dir.name
            dspf_file = window_dir / "all_nets.dspf"
            if dspf_file.exists():
                window_dirs.append((window_id, window_dir))
            else:
                print(f"Warning: Skipping {window_dir} - no all_nets.dspf found", file=sys.stderr)

    # Sort by window ID numerically when possible
    def sort_key(item):
        window_id = item[0]
        try:
            numeric_part = ''.join(filter(str.isdigit, window_id))
            return int(numeric_part) if numeric_part else window_id
        except ValueError:
            return window_id

    return sorted(window_dirs, key=sort_key)


def convert_single_window(
    window_id: str,
    window_dir: Path,
    output_dir: Path,
    *,
    coupling_threshold_ratio: float = DEFAULT_COUPLING_THRESHOLD_RATIO,
    **options
) -> Tuple[str, bool, str, Optional[str]]:
    """Convert a single window from DSPF to SPEF format."""

    dspf_file = window_dir / "all_nets.dspf"

    try:
        # Check if output file already exists
        output_file = output_dir / f"{window_id}.spef"
        if output_file.exists() and not options.get('overwrite', False):
            return window_id, True, "Already exists", None, 0

        # Parse DSPF file
        try:
            with dspf_file.open("r", encoding="utf-8", errors="ignore") as f:
                lines = f.readlines()
        except OSError as exc:
            return window_id, False, f"Failed to read {dspf_file}: {exc}", str(exc)

        drop_nets = options.get('drop_nets', [])
        threshold_f = options.get('threshold', 0.0)

        self_cap_f, coupling_f = parse_raphael(
            lines,
            drop_nets=drop_nets,
            threshold_f=threshold_f,
        )

        if options.get('align_names_with_spef'):
            try:
                with open(options['align_names_with_spef'], "r", encoding="utf-8", errors="ignore") as f:
                    ref_lines = f.readlines()
            except OSError:
                ref_lines = []
            if ref_lines:
                self_cap_f, coupling_f = align_with_spef_name_map(
                    self_cap_f,
                    coupling_f,
                    ref_lines,
                )

        # Include all nets that have capacitance data, including GROUND
        # Also include nets that appear in couplings (like GROUND)
        all_nets = set(self_cap_f.keys())
        for net_a, net_b in coupling_f.keys():
            all_nets.add(net_a)
            all_nets.add(net_b)

        # Filter out dropped nets
        # Keep GROUND in coupling_f but exclude from nets list that get self-capacitance
        regular_nets = sorted(n for n in all_nets if n not in drop_nets and n != "GROUND")
        # For nets with self-capacitance entries only (exclude GROUND)
        nets = regular_nets
        if not nets:
            return window_id, False, "No nets parsed after filtering", None, 0

        # Write SPEF file
        with output_file.open("w", encoding="utf-8") as out:
            removed_couplings_count = write_spef(
                out,
                design=window_id,
                nets=nets,
                self_cap_f=self_cap_f,
                coupling_f=coupling_f,
                coupling_threshold_ratio=coupling_threshold_ratio,
            )

        return window_id, True, "Converted successfully", None, removed_couplings_count

    except Exception as e:
        return window_id, False, f"Exception: {str(e)}", str(e), 0


def main(argv: Optional[List[str]] = None) -> int:
    """Main entry point for the batch conversion script."""

    ap = argparse.ArgumentParser(
        description="Convert Raphael DSPF output to SPEF format for multiple windows.",
        epilog="""
Examples:
  # Basic usage - convert all windows
  python raphael_to_spef.py datasets/nangate45/small/out_raphael datasets/nangate45/small/labels_raphael

  # With threshold filtering
  python raphael_to_spef.py \\
    datasets/nangate45/small/out_raphael \\
    datasets/nangate45/small/labels_raphael \\
    --threshold 1e-18 \\
    --overwrite

  # Custom pattern
  python raphael_to_spef.py \\
    /path/to/raphael/output \\
    /path/to/spef/output \\
    --pattern "W[0-9]*"
        """,
        formatter_class=argparse.RawDescriptionHelpFormatter
    )

    # Required arguments
    ap.add_argument("input_dir", help="Directory containing window subdirectories with all_nets.dspf files")
    ap.add_argument("output_dir", help="Directory to write SPEF files to")

    # Processing options
    ap.add_argument(
        "--pattern",
        default="W*",
        help="Glob pattern for window directories (default: 'W*')"
    )
    ap.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing SPEF files"
    )

    # Filtering options
    ap.add_argument(
        "--drop",
        action="append",
        default=[],
        help="Drop nets by exact name from the output (can be repeated)"
    )
    ap.add_argument(
        "--threshold",
        type=float,
        default=0.0,
        help="Ignore |C| below this magnitude (in F) when parsing"
    )
    ap.add_argument(
        "--coupling-threshold",
        type=float,
        default=DEFAULT_COUPLING_THRESHOLD_RATIO,
        help=f"Skip coupling capacitances below this percentage of self capacitance (default: {DEFAULT_COUPLING_THRESHOLD_RATIO * 100:.1f}%%)"
    )
    ap.add_argument(
        "--align-names-with-spef",
        help="Optional SPEF whose *NAME_MAP will guide name alignment (e.g. map Net.N -> netN)"
    )

    args = ap.parse_args(argv)

    # Validate input directory
    input_dir = Path(args.input_dir).resolve()
    if not input_dir.is_dir():
        print(f"Error: Input directory not found: {input_dir}", file=sys.stderr)
        return 1

    # Prepare output directory
    output_dir = Path(args.output_dir).resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    # Prepare conversion options
    options = {
        'drop_nets': args.drop,
        'threshold': args.threshold,
        'coupling_threshold_ratio': args.coupling_threshold,
        'align_names_with_spef': args.align_names_with_spef,
        'overwrite': args.overwrite,
    }

    # Remove None values
    options = {k: v for k, v in options.items() if v is not None}

    print(f"Converting Raphael DSPF to SPEF")
    print(f"  Input directory:      {input_dir}")
    print(f"  Output directory:     {output_dir}")
    print(f"  Pattern:              {args.pattern}")
    if args.threshold > 0:
        print(f"  Magnitude threshold: {args.threshold:.2e} F")
    if args.coupling_threshold != DEFAULT_COUPLING_THRESHOLD_RATIO:
        print(f"  Coupling threshold:  {args.coupling_threshold:.1%}")
    print()

    # Find all window directories
    try:
        windows = find_window_directories(input_dir, args.pattern)
    except ValueError as e:
        print(f"Error: {e}", file=sys.stderr)
        return 1

    if not windows:
        print(f"No window directories found in {input_dir} with pattern '{args.pattern}'", file=sys.stderr)
        return 1

    print(f"Found {len(windows)} windows to convert")

    # Process windows sequentially
    success_count = 0
    failure_count = 0
    failed_windows = []
    total_removed_couplings = 0

    with tqdm(windows, desc="Converting windows", unit="window") as pbar:
        for window_id, window_dir in windows:
            result = convert_single_window(window_id, window_dir, output_dir, **options)
            w_id, success, message, error, removed_count = result

            if success:
                success_count += 1
                total_removed_couplings += removed_count
                # Report removed couplings for this window
                if removed_count > 0:
                    tqdm.write(f"[raphael_to_spef] {window_id}: Removed {removed_count:,} coupling capacitances ({options.get('coupling_threshold_ratio', DEFAULT_COUPLING_THRESHOLD_RATIO):.1%} threshold)")
            else:
                failure_count += 1
                failed_windows.append((w_id, error))

            pbar.set_postfix({"status": "✓" if success else "✗", "msg": message})
            pbar.update()

    # Print summary
    print(f"\nConversion Summary:")
    print(f"  Successful:  {success_count}")
    print(f"  Failed:      {failure_count}")
    print(f"  Total:       {success_count + failure_count}")

    if total_removed_couplings > 0:
        print(f"  Total removed coupling capacitances: {total_removed_couplings:,} ({options.get('coupling_threshold_ratio', DEFAULT_COUPLING_THRESHOLD_RATIO):.1%} threshold)")

    if failed_windows:
        print(f"\nFailed windows:")
        for window_id, error in failed_windows[:10]:  # Show first 10 errors
            print(f"  {window_id}: {error}")
        if len(failed_windows) > 10:
            print(f"  ... and {len(failed_windows) - 10} more")

    return 0 if failure_count == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())